__title__ = "mypackage"
__version__ = "0.0.1"
__author__ = "Sergio Bautista"
__email__ = "sergio.bautista@logicsource.com"
__description__ = "Package to learn how to use packages with gtihub"
__url__ = "https://github.com/sergiobautistalsi/first_package"